/**
 * Maps modern ISO 3166-1 NUMERIC country codes (strings with leading zeros)
 * to their 1938–1939 pre-WWII geopolitical entities.
 *
 * Used to transform a modern Natural Earth / world-atlas GeoJSON into a
 * historically accurate political map of the world just before World War II.
 *
 * Fields per entry:
 *   id         – lowercase identifier of the controlling power
 *   name       – display name as known in 1938–1939
 *   controller – nation ID of the controlling power (same as id)
 *   alliance   – "axis" | "allies" | "soviet" | "neutral" | "neutral_axis" | "neutral_allied" | "us"
 *   type       – "core" | "colony" | "protectorate" | "mandate" | "puppet" | "dominion" | "occupied"
 */

export const countryMapping = {

  // ── A ──────────────────────────────────────────────────────────────────────

  "004": { id: "afghanistan", name: "Afghanistan", controller: "afghanistan", alliance: "neutral", type: "core" },
  "008": { id: "italy", name: "Albania", controller: "italy", alliance: "axis", type: "puppet" },
  "010": { id: "unclaimed", name: "Antarctica", controller: "unclaimed", alliance: "neutral", type: "core" },
  "012": { id: "france", name: "Algeria", controller: "france", alliance: "allies", type: "colony" },
  "024": { id: "portugal", name: "Angola", controller: "portugal", alliance: "neutral", type: "colony" },
  "031": { id: "soviet_union", name: "Azerbaijan SSR", controller: "soviet_union", alliance: "soviet", type: "core" },
  "032": { id: "argentina", name: "Argentina", controller: "argentina", alliance: "neutral", type: "core" },
  "036": { id: "australia", name: "Australia", controller: "australia", alliance: "allies", type: "dominion" },
  "040": { id: "germany", name: "Austria (Annexed)", controller: "germany", alliance: "axis", type: "occupied" },
  "044": { id: "uk", name: "Bahamas", controller: "uk", alliance: "allies", type: "colony" },
  "050": { id: "uk", name: "British India", controller: "uk", alliance: "allies", type: "colony" },
  "051": { id: "soviet_union", name: "Armenian SSR", controller: "soviet_union", alliance: "soviet", type: "core" },
  "056": { id: "belgium", name: "Belgium", controller: "belgium", alliance: "neutral", type: "core" },
  "064": { id: "uk", name: "Bhutan", controller: "uk", alliance: "allies", type: "protectorate" },
  "068": { id: "bolivia", name: "Bolivia", controller: "bolivia", alliance: "neutral", type: "core" },
  "070": { id: "yugoslavia", name: "Yugoslavia", controller: "yugoslavia", alliance: "neutral", type: "core" },
  "072": { id: "uk", name: "Bechuanaland", controller: "uk", alliance: "allies", type: "protectorate" },
  "076": { id: "brazil", name: "Brazil", controller: "brazil", alliance: "neutral", type: "core" },
  "084": { id: "uk", name: "British Honduras", controller: "uk", alliance: "allies", type: "colony" },
  "090": { id: "uk", name: "Solomon Islands", controller: "uk", alliance: "allies", type: "protectorate" },
  "096": { id: "uk", name: "Brunei", controller: "uk", alliance: "allies", type: "protectorate" },

  // ── B ──────────────────────────────────────────────────────────────────────

  "100": { id: "bulgaria", name: "Bulgaria", controller: "bulgaria", alliance: "neutral_axis", type: "core" },
  "104": { id: "uk", name: "Burma", controller: "uk", alliance: "allies", type: "colony" },
  "108": { id: "belgium", name: "Ruanda-Urundi", controller: "belgium", alliance: "neutral", type: "mandate" },
  "112": { id: "soviet_union", name: "Belorussian SSR", controller: "soviet_union", alliance: "soviet", type: "core" },
  "116": { id: "france", name: "Cambodia (French Indochina)", controller: "france", alliance: "allies", type: "colony" },
  "120": { id: "france", name: "French Cameroon", controller: "france", alliance: "allies", type: "mandate" },
  "124": { id: "canada", name: "Canada", controller: "canada", alliance: "allies", type: "dominion" },
  "140": { id: "france", name: "Ubangi-Shari", controller: "france", alliance: "allies", type: "colony" },
  "144": { id: "uk", name: "Ceylon", controller: "uk", alliance: "allies", type: "colony" },
  "148": { id: "france", name: "Chad", controller: "france", alliance: "allies", type: "colony" },
  "152": { id: "chile", name: "Chile", controller: "chile", alliance: "neutral", type: "core" },
  "156": { id: "china", name: "Republic of China", controller: "china", alliance: "allies", type: "core" },
  "158": { id: "japan", name: "Formosa", controller: "japan", alliance: "axis", type: "colony" },
  "170": { id: "colombia", name: "Colombia", controller: "colombia", alliance: "neutral", type: "core" },
  "174": { id: "france", name: "Comoros", controller: "france", alliance: "allies", type: "colony" },
  "178": { id: "france", name: "Middle Congo", controller: "france", alliance: "allies", type: "colony" },
  "180": { id: "belgium", name: "Belgian Congo", controller: "belgium", alliance: "neutral", type: "colony" },
  "188": { id: "costa_rica", name: "Costa Rica", controller: "costa_rica", alliance: "neutral", type: "core" },
  "191": { id: "yugoslavia", name: "Yugoslavia", controller: "yugoslavia", alliance: "neutral", type: "core" },
  "192": { id: "cuba", name: "Cuba", controller: "cuba", alliance: "neutral", type: "core" },
  "196": { id: "uk", name: "Cyprus", controller: "uk", alliance: "allies", type: "colony" },

  // ── C / D ──────────────────────────────────────────────────────────────────

  "203": { id: "germany", name: "Protectorate of Bohemia and Moravia", controller: "germany", alliance: "axis", type: "protectorate" },
  "204": { id: "france", name: "Dahomey", controller: "france", alliance: "allies", type: "colony" },
  "208": { id: "denmark", name: "Denmark", controller: "denmark", alliance: "neutral", type: "core" },
  "214": { id: "dominican_republic", name: "Dominican Republic", controller: "dominican_republic", alliance: "neutral", type: "core" },
  "218": { id: "ecuador", name: "Ecuador", controller: "ecuador", alliance: "neutral", type: "core" },
  "222": { id: "el_salvador", name: "El Salvador", controller: "el_salvador", alliance: "neutral", type: "core" },
  "226": { id: "spain", name: "Spanish Guinea", controller: "spain", alliance: "neutral_axis", type: "colony" },
  "231": { id: "italy", name: "Italian East Africa", controller: "italy", alliance: "axis", type: "occupied" },
  "232": { id: "italy", name: "Eritrea", controller: "italy", alliance: "axis", type: "colony" },
  "233": { id: "estonia", name: "Estonia", controller: "estonia", alliance: "neutral", type: "core" },
  "238": { id: "uk", name: "Falkland Islands", controller: "uk", alliance: "allies", type: "colony" },
  "242": { id: "uk", name: "Fiji", controller: "uk", alliance: "allies", type: "colony" },
  "246": { id: "finland", name: "Finland", controller: "finland", alliance: "neutral", type: "core" },
  "250": { id: "france", name: "France", controller: "france", alliance: "allies", type: "core" },
  "260": { id: "france", name: "French Southern Territories", controller: "france", alliance: "allies", type: "colony" },
  "262": { id: "france", name: "French Somaliland", controller: "france", alliance: "allies", type: "colony" },
  "266": { id: "france", name: "Gabon", controller: "france", alliance: "allies", type: "colony" },
  "268": { id: "soviet_union", name: "Georgian SSR", controller: "soviet_union", alliance: "soviet", type: "core" },
  "270": { id: "uk", name: "Gambia", controller: "uk", alliance: "allies", type: "colony" },
  "275": { id: "uk", name: "Palestine Mandate", controller: "uk", alliance: "allies", type: "mandate" },
  "276": { id: "germany", name: "German Reich", controller: "germany", alliance: "axis", type: "core" },
  "288": { id: "uk", name: "Gold Coast", controller: "uk", alliance: "allies", type: "colony" },

  // ── G / H / I ──────────────────────────────────────────────────────────────

  "300": { id: "greece", name: "Greece", controller: "greece", alliance: "neutral_allied", type: "core" },
  "304": { id: "denmark", name: "Greenland", controller: "denmark", alliance: "neutral", type: "colony" },
  "320": { id: "guatemala", name: "Guatemala", controller: "guatemala", alliance: "neutral", type: "core" },
  "324": { id: "france", name: "French Guinea", controller: "france", alliance: "allies", type: "colony" },
  "328": { id: "uk", name: "British Guiana", controller: "uk", alliance: "allies", type: "colony" },
  "332": { id: "haiti", name: "Haiti", controller: "haiti", alliance: "neutral", type: "core" },
  "340": { id: "honduras", name: "Honduras", controller: "honduras", alliance: "neutral", type: "core" },
  "344": { id: "uk", name: "Hong Kong", controller: "uk", alliance: "allies", type: "colony" },
  "348": { id: "hungary", name: "Hungary", controller: "hungary", alliance: "neutral_axis", type: "core" },
  "352": { id: "iceland", name: "Iceland", controller: "iceland", alliance: "neutral", type: "core" },
  "356": { id: "uk", name: "British India", controller: "uk", alliance: "allies", type: "colony" },
  "360": { id: "netherlands", name: "Dutch East Indies", controller: "netherlands", alliance: "neutral", type: "colony" },
  "364": { id: "iran", name: "Iran", controller: "iran", alliance: "neutral", type: "core" },
  "368": { id: "iraq", name: "Iraq", controller: "iraq", alliance: "neutral_allied", type: "core" },
  "372": { id: "ireland", name: "Irish Free State", controller: "ireland", alliance: "neutral", type: "core" },
  "376": { id: "uk", name: "Palestine Mandate", controller: "uk", alliance: "allies", type: "mandate" },
  "380": { id: "italy", name: "Kingdom of Italy", controller: "italy", alliance: "axis", type: "core" },
  "384": { id: "france", name: "Côte d'Ivoire", controller: "france", alliance: "allies", type: "colony" },
  "388": { id: "uk", name: "Jamaica", controller: "uk", alliance: "allies", type: "colony" },
  "392": { id: "japan", name: "Empire of Japan", controller: "japan", alliance: "axis", type: "core" },
  "398": { id: "soviet_union", name: "Kazakh SSR", controller: "soviet_union", alliance: "soviet", type: "core" },
  "400": { id: "uk", name: "Transjordan", controller: "uk", alliance: "allies", type: "mandate" },
  "404": { id: "uk", name: "Kenya Colony", controller: "uk", alliance: "allies", type: "colony" },
  "408": { id: "japan", name: "Korea (Japanese)", controller: "japan", alliance: "axis", type: "colony" },
  "410": { id: "japan", name: "Korea (Japanese)", controller: "japan", alliance: "axis", type: "colony" },
  "414": { id: "uk", name: "Kuwait", controller: "uk", alliance: "allies", type: "protectorate" },
  "417": { id: "soviet_union", name: "Kirghiz SSR", controller: "soviet_union", alliance: "soviet", type: "core" },
  "418": { id: "france", name: "Laos (French Indochina)", controller: "france", alliance: "allies", type: "colony" },
  "422": { id: "france", name: "Lebanon Mandate", controller: "france", alliance: "allies", type: "mandate" },
  "426": { id: "uk", name: "Basutoland", controller: "uk", alliance: "allies", type: "protectorate" },
  "428": { id: "latvia", name: "Latvia", controller: "latvia", alliance: "neutral", type: "core" },
  "430": { id: "liberia", name: "Liberia", controller: "liberia", alliance: "neutral", type: "core" },
  "434": { id: "italy", name: "Libya", controller: "italy", alliance: "axis", type: "colony" },
  "440": { id: "lithuania", name: "Lithuania", controller: "lithuania", alliance: "neutral", type: "core" },
  "442": { id: "luxembourg", name: "Luxembourg", controller: "luxembourg", alliance: "neutral", type: "core" },

  // ── L / M / N ──────────────────────────────────────────────────────────────

  "450": { id: "france", name: "Madagascar", controller: "france", alliance: "allies", type: "colony" },
  "454": { id: "uk", name: "Nyasaland", controller: "uk", alliance: "allies", type: "protectorate" },
  "458": { id: "uk", name: "Malaya", controller: "uk", alliance: "allies", type: "colony" },
  "462": { id: "uk", name: "Maldives", controller: "uk", alliance: "allies", type: "protectorate" },
  "466": { id: "france", name: "French Sudan", controller: "france", alliance: "allies", type: "colony" },
  "470": { id: "uk", name: "Malta", controller: "uk", alliance: "allies", type: "colony" },
  "478": { id: "france", name: "Mauritania", controller: "france", alliance: "allies", type: "colony" },
  "484": { id: "mexico", name: "Mexico", controller: "mexico", alliance: "neutral", type: "core" },
  "496": { id: "soviet_union", name: "Mongolian People's Republic", controller: "soviet_union", alliance: "soviet", type: "puppet" },
  "498": { id: "romania", name: "Romania (Bessarabia)", controller: "romania", alliance: "neutral_allied", type: "core" },
  "499": { id: "yugoslavia", name: "Yugoslavia", controller: "yugoslavia", alliance: "neutral", type: "core" },
  "504": { id: "france", name: "French Morocco", controller: "france", alliance: "allies", type: "protectorate" },
  "508": { id: "portugal", name: "Mozambique", controller: "portugal", alliance: "neutral", type: "colony" },
  "512": { id: "uk", name: "Muscat and Oman", controller: "uk", alliance: "allies", type: "protectorate" },
  "516": { id: "south_africa", name: "South-West Africa", controller: "south_africa", alliance: "allies", type: "mandate" },
  "524": { id: "nepal", name: "Nepal", controller: "nepal", alliance: "neutral", type: "core" },
  "528": { id: "netherlands", name: "Netherlands", controller: "netherlands", alliance: "neutral", type: "core" },
  "540": { id: "france", name: "New Caledonia", controller: "france", alliance: "allies", type: "colony" },
  "548": { id: "uk", name: "New Hebrides", controller: "uk", alliance: "allies", type: "colony" },
  "554": { id: "new_zealand", name: "New Zealand", controller: "new_zealand", alliance: "allies", type: "dominion" },
  "558": { id: "nicaragua", name: "Nicaragua", controller: "nicaragua", alliance: "neutral", type: "core" },
  "562": { id: "france", name: "Niger", controller: "france", alliance: "allies", type: "colony" },
  "566": { id: "uk", name: "Nigeria", controller: "uk", alliance: "allies", type: "colony" },
  "578": { id: "norway", name: "Norway", controller: "norway", alliance: "neutral", type: "core" },

  // ── O / P ──────────────────────────────────────────────────────────────────

  "586": { id: "uk", name: "British India", controller: "uk", alliance: "allies", type: "colony" },
  "591": { id: "panama", name: "Panama", controller: "panama", alliance: "neutral", type: "core" },
  "598": { id: "australia", name: "Territory of New Guinea", controller: "australia", alliance: "allies", type: "mandate" },
  "600": { id: "paraguay", name: "Paraguay", controller: "paraguay", alliance: "neutral", type: "core" },
  "604": { id: "peru", name: "Peru", controller: "peru", alliance: "neutral", type: "core" },
  "608": { id: "usa", name: "Philippine Commonwealth", controller: "usa", alliance: "us", type: "colony" },
  "616": { id: "poland", name: "Poland", controller: "poland", alliance: "allies", type: "core" },
  "620": { id: "portugal", name: "Portugal", controller: "portugal", alliance: "neutral", type: "core" },
  "624": { id: "portugal", name: "Portuguese Guinea", controller: "portugal", alliance: "neutral", type: "colony" },
  "626": { id: "portugal", name: "Portuguese Timor", controller: "portugal", alliance: "neutral", type: "colony" },
  "630": { id: "usa", name: "Puerto Rico", controller: "usa", alliance: "us", type: "colony" },
  "634": { id: "uk", name: "Qatar", controller: "uk", alliance: "allies", type: "protectorate" },

  // ── R / S ──────────────────────────────────────────────────────────────────

  "642": { id: "romania", name: "Romania", controller: "romania", alliance: "neutral_allied", type: "core" },
  "643": { id: "soviet_union", name: "Soviet Union", controller: "soviet_union", alliance: "soviet", type: "core" },
  "646": { id: "belgium", name: "Ruanda-Urundi", controller: "belgium", alliance: "neutral", type: "mandate" },
  "682": { id: "saudi_arabia", name: "Saudi Arabia", controller: "saudi_arabia", alliance: "neutral", type: "core" },
  "686": { id: "france", name: "Senegal", controller: "france", alliance: "allies", type: "colony" },
  "688": { id: "yugoslavia", name: "Yugoslavia", controller: "yugoslavia", alliance: "neutral", type: "core" },
  "694": { id: "uk", name: "Sierra Leone", controller: "uk", alliance: "allies", type: "colony" },
  "703": { id: "germany", name: "Slovak Republic", controller: "germany", alliance: "axis", type: "puppet" },
  "704": { id: "france", name: "French Indochina", controller: "france", alliance: "allies", type: "colony" },
  "705": { id: "yugoslavia", name: "Yugoslavia", controller: "yugoslavia", alliance: "neutral", type: "core" },
  "706": { id: "italy", name: "Italian Somaliland", controller: "italy", alliance: "axis", type: "colony" },
  "710": { id: "south_africa", name: "South Africa", controller: "south_africa", alliance: "allies", type: "dominion" },
  "716": { id: "uk", name: "Southern Rhodesia", controller: "uk", alliance: "allies", type: "colony" },
  "724": { id: "spain", name: "Spain", controller: "spain", alliance: "neutral_axis", type: "core" },
  "728": { id: "uk", name: "Anglo-Egyptian Sudan", controller: "uk", alliance: "allies", type: "colony" },
  "729": { id: "uk", name: "Anglo-Egyptian Sudan", controller: "uk", alliance: "allies", type: "colony" },
  "732": { id: "spain", name: "Spanish Sahara", controller: "spain", alliance: "neutral_axis", type: "colony" },
  "740": { id: "netherlands", name: "Dutch Guiana", controller: "netherlands", alliance: "neutral", type: "colony" },
  "748": { id: "uk", name: "Swaziland", controller: "uk", alliance: "allies", type: "protectorate" },
  "752": { id: "sweden", name: "Sweden", controller: "sweden", alliance: "neutral", type: "core" },
  "756": { id: "switzerland", name: "Switzerland", controller: "switzerland", alliance: "neutral", type: "core" },
  "760": { id: "france", name: "Syria Mandate", controller: "france", alliance: "allies", type: "mandate" },
  "762": { id: "soviet_union", name: "Tajik SSR", controller: "soviet_union", alliance: "soviet", type: "core" },
  "764": { id: "thailand", name: "Siam", controller: "thailand", alliance: "neutral", type: "core" },
  "768": { id: "france", name: "French Togoland", controller: "france", alliance: "allies", type: "mandate" },

  // ── T / U / V / W / Y / Z ─────────────────────────────────────────────────

  "780": { id: "uk", name: "Trinidad and Tobago", controller: "uk", alliance: "allies", type: "colony" },
  "784": { id: "uk", name: "Trucial States", controller: "uk", alliance: "allies", type: "protectorate" },
  "788": { id: "france", name: "Tunisia", controller: "france", alliance: "allies", type: "protectorate" },
  "792": { id: "turkey", name: "Turkey", controller: "turkey", alliance: "neutral_allied", type: "core" },
  "795": { id: "soviet_union", name: "Turkmen SSR", controller: "soviet_union", alliance: "soviet", type: "core" },
  "800": { id: "uk", name: "Uganda", controller: "uk", alliance: "allies", type: "protectorate" },
  "804": { id: "soviet_union", name: "Ukrainian SSR", controller: "soviet_union", alliance: "soviet", type: "core" },
  "807": { id: "yugoslavia", name: "Yugoslavia", controller: "yugoslavia", alliance: "neutral", type: "core" },
  "818": { id: "egypt", name: "Kingdom of Egypt", controller: "egypt", alliance: "neutral_allied", type: "core" },
  "826": { id: "uk", name: "United Kingdom", controller: "uk", alliance: "allies", type: "core" },
  "834": { id: "uk", name: "Tanganyika", controller: "uk", alliance: "allies", type: "mandate" },
  "840": { id: "usa", name: "United States", controller: "usa", alliance: "us", type: "core" },
  "854": { id: "france", name: "Upper Volta", controller: "france", alliance: "allies", type: "colony" },
  "858": { id: "uruguay", name: "Uruguay", controller: "uruguay", alliance: "neutral", type: "core" },
  "860": { id: "soviet_union", name: "Uzbek SSR", controller: "soviet_union", alliance: "soviet", type: "core" },
  "862": { id: "venezuela", name: "Venezuela", controller: "venezuela", alliance: "neutral", type: "core" },
  "882": { id: "new_zealand", name: "Western Samoa", controller: "new_zealand", alliance: "allies", type: "mandate" },
  "887": { id: "yemen", name: "Kingdom of Yemen", controller: "yemen", alliance: "neutral", type: "core" },
  "894": { id: "uk", name: "Northern Rhodesia", controller: "uk", alliance: "allies", type: "protectorate" },
};
